# Generated by Django 4.2.6 on 2023-11-27 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256, unique=True)),
                ('email_address', models.EmailField(max_length=256, unique=True)),
                ('secure_password', models.CharField(blank=True, max_length=256, null=True)),
                ('given_name', models.CharField(blank=True, max_length=256, null=True)),
                ('family_name', models.CharField(blank=True, max_length=256, null=True)),
                ('identification_image', models.ImageField(blank=True, null=True, upload_to='user_id_images/')),
                ('preferences', models.JSONField(blank=True, default=list)),
                ('digital_assets', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_price_cad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_cap', models.IntegerField()),
                ('market_cap_rank', models.PositiveIntegerField()),
                ('fully_diluted_valuation', models.IntegerField(blank=True, null=True)),
                ('total_volume', models.IntegerField(blank=True, null=True)),
                ('high_24h', models.IntegerField(blank=True, null=True)),
                ('low_24h', models.IntegerField(blank=True, null=True)),
                ('price_change_24h', models.IntegerField(blank=True, null=True)),
                ('price_change_percentage_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_cap_change_24h', models.IntegerField(blank=True, null=True)),
                ('market_cap_change_percentage_24h', models.IntegerField(blank=True, null=True)),
                ('circulating_supply', models.IntegerField(blank=True, null=True)),
                ('total_supply', models.IntegerField(blank=True, null=True)),
                ('max_supply', models.IntegerField(blank=True, null=True)),
                ('ath', models.IntegerField(blank=True, null=True)),
                ('ath_change_percentage', models.IntegerField(blank=True, null=True)),
                ('ath_date', models.DateTimeField(blank=True, null=True)),
                ('atl', models.IntegerField(blank=True, null=True)),
                ('atl_change_percentage', models.IntegerField(blank=True, null=True)),
                ('atl_date', models.DateTimeField(blank=True, null=True)),
                ('roi', models.FloatField(null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MoneyMakers.accountprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('purchase', 'Purchase'), ('sell', 'Sell')], default='purchase', max_length=8)),
                ('digital_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyMakers.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyMakers.accountprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('activity_timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyMakers.accountprofile')),
            ],
        ),
    ]
